email:
  enabled: false
  smtp_server: ""
  smtp_port: 587
  username: ""
  password: ""
  from_addr: ""
  to_addrs: []

telegram:
  enabled: false
  bot_token: ""
  chat_id: ""

discord:
  enabled: false
  webhook_url: ""

slack:
  enabled: false
  webhook_url: ""

webhook:
  enabled: false
  url: ""   # generic webhook (e.g., ELK/Splunk HTTP Event Collector)
